### ISSUE TITLE
Smart on FHIR with patient/*.write scope should be more restrictive.

### ISSUE THREAD

**Issue by d0roppe** [LinuxForHealth/FHIR#3593]
**Is your feature request related to a problem? Please describe.**
You should not be able to create other patients with a post even if you are linking the patient with your patient.  As this creates a new patient in the provider DB, that is not known to the provider. 
Same with non Patient Compartment Resource like Organization,  you should not be able to create a Organization with patient/*.write scope.

Current implementation allows you to create these resource, but does not allow you to modify them or in the case of the Patient to read it. 

**Describe the solution you'd like**
If you have patient/*.write scope you should only be able to create resources in the current patient compartment no other resource.

**Comment by lmsurpre** [comment]
Currently we use the same policy enforcement for read and write scopes.  Resource created via `patient/*.write` should be readable via `patient/*.read` and updatable with `patient/*.*`

from https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Inferno.20requiring.20patient.20focus.20for.20non-patient.20resources

> Currently scopes like patient/Organization.read are allowed/valid in SMART with the interpretation of something like "Organizations the EHR determines you need access to in order to make in-context patient record".

As a generic FHIR server, we have no way to determine which Organizations make up the 'in-context patient record' and so we leave that to implementers.  This means that, for non-patient-copartment resource types, a `patient/` scope will currently behave the same as a `user/` scope...open access (unless you layer a permission model on top).

**Comment by lmsurpre** [comment]
The "patient/Patient.write" part of this one was addressed under #3592

For non-patient compartment resource types like Organization and Location, operators can prevent users from writing those in one of two ways:
1. don't grant scopes that allow users to write these.  e.g. explicitly enumerate the resource types that can be written instead of granting `patient/*.write`
2. explicitly configure which "interactions" are supported for each resource type via `fhirServer/resources/<resourceType>/interactions` in fhir-server-config.json (i.e. omit "create", "update", and "delete" from the list)
