### ISSUE TITLE
Display portion of CodeableConcept is stored as a token not a string

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3710]
**Describe the bug**
For token: :text (the match does a partial searches on the text portion of a CodeableConcept or the display portion of a Coding), instead of the default search which uses codes.

The value is extracted as a token parameter value and is stored in the xx_resource_token_refs and whole-system resource_token_refs tables.

See JDBCWholeSystemSearchTest>AbstractWholeSystemSearchTest.testSearchAllUsingTagModifierText.

**Environment**
Which version of IBM FHIR Server? 5.0.0 pre-release

**To Reproduce**
1. Debug JDBCWholeSystemSearchTest and see how the search parameter is extracted and stored.

**Expected behavior**
Should this be treated as a string?

**Additional context**
Consider the implications of treated this as a string, including how this will affect searches.

**Comment by lmsurpre** [comment]
Question:  does it apply to all tokens or just system-level ones (like `_tag:text`)?

TODO:  Confirm we use string search semantics (begins-with, case-insensitive) for this search param even though it exists in tokens.   

Pretty sure we don't do the "begins-with" part of this one which is why its technically a bug.
For case-sensitivity, CodeSystems can say whether they are case-sensitive or not.  For `_tag:text` there may be no underlying CodeSystem in which case we use our default...would need to investigate to see if thats case-sensitive or not.

**Comment by lmsurpre** [comment]
I confirmed that we *do* use case-insensitive, begins-with semantics when searching with the `:text` modifier at both the instance and "whole-system" level.

First I created a Patient with a tag like:
```
					"tag": [
						{
							"system": "http://example.com",
							"code": "text",
							"display": "Text"
						}
```
and confirmed I can find that with a search like `GET {{base}}?_tag:text=te`
Next I created an Observation with a code like:
```
				"code": {
					"coding": [
						{
							"system": "http://loinc.org",
							"code": "85354-9",
							"display": "Blood pressure panel with all children optional"
						}
					],
					"text": "Blood pressure systolic & diastolic"
				},
```
and confirmed I can find that with searches like `GET {{base}}/Observation?code:text=blood pressure sys` (CodeableConcept.text) and `GET {{base}}/Observation?code:text=blood pressure panel` (CodeableConcept.coding.display)



:text | The search parameter is processed as a string that searches text associated with the code/value - either CodeableConcept.text, Coding.display, or Identifier.type.text. In this case, the search functions as a normal string search
-- | --


:text	The search parameter is processed as a string that searches text associated with the code/value - either CodeableConcept.text, Coding.display, or Identifier.type.text. In this case, the search functions as a [normal string search](https://build.fhir.org/search.html#string

I also re-read the spec on this one and I don't think `:text` needs to be CodeSystem case-sensitivity-aware (since it indexes both Coding.display AND CodeableConcept.text)

Modifier | Use
-- | --
:text | The search parameter is processed as a string that searches text associated with the code/value - either CodeableConcept.text, Coding.display, or Identifier.type.text. In this case, the search functions as a normal string search

net:  functionally, I think this one is working as expected.
