### ISSUE TITLE
Interceptor data sent back to the caller

### ISSUE THREAD

**Issue by albvegli** [LinuxForHealth/FHIR#3787]
Using the interceptor I need to add more information to the returned afterSearch (bundle) data.
I have generated a new bundle but cannot send it to the caller. Everything I've tried to do doesn't change the packet sent to the caller.
How can I update the packet sent back to the caller?

**Comment by punktilious** [comment]
@albvegli thank you for opening this issue. Unfortunately the current code does not return the updated resource if it is changed by the interceptor. In FHIRRestHelper:

```
            // Invoke the 'afterSearch' interceptor methods.
            getInterceptorMgr().fireAfterSearchEvent(event);

            // Commit our transaction if we started one before.
            txn.commit();
            txn = null;

            return bundle;
```
We'll add this to our backlog. The team needs to discuss this to see if there are any implications for supporting this behavior. To make sure we properly consider your scenario, could you provide more detail on what changes your interceptor needs to make to the bundle?

**Comment by punktilious** [comment]
Thanks. It's an interesting point you raise about interceptors invoking interactions which then cause nested calls to the interceptor.  It seems like it would be possible to track this in the request context, which would make it a lot easier for an implementer (you) to understand where you are and react appropriately. I'll discuss with the team and get back to you.

**Comment by lmsurpre** [comment]
@albvegli how are you performing the search from within your interceptor.

I would have expected your interceptor to use `event.getPersistenceImpl()` to get the FHIRPersistence implementation from the FHIRPersistenceEvent.

Its a little tricky to set up the FHIRSearchContext, but it should be possible to invoke "FHIRPersistence.search" from your interceptor and avoid going all the way back out through the REST layer.  If done this way, there is no "re-entry" because the interceptors are invoked outside of the persistence layer.

Let us know.

**Comment by albvegli** [comment]
Yes, I’m usig event.getPersistenceImpl().

Patient pat = null;
try {
  FHIRRestHelper helper = new FHIRRestHelper(event.getPersistenceImpl(),searchHelper); 
  Resource resource = helper.doRead("Patient", id, false, false, null, null).getResource();
  pat = (Patient) resource;
} catch (Exception e) {
  e.printStackTrace();
}

I have now stopped developing this feature due to the inability to return additional information. If I need it later I will try to follow your advice.
Thank you.

**Comment by punktilious** [comment]
As @lmsurpre mentioned, you can use the persistence layer to perform the read directly:
```
    /**
     * Retrieves the most recent version of a FHIR Resource from the datastore.
     *
     * @param context the FHIRPersistenceContext instance associated with the current request
     * @param resourceType the resource type of the Resource instance to be retrieved
     * @param logicalId the logical id of the Resource instance to be retrieved
     * @return a SingleResourceResult with a ResourceResult populated from from the datastore and/or
     *         an OperationOutcome with hints, warnings, or errors related to the interaction
     * @throws FHIRPersistenceException
     * @implSpec Reading a non-existent resource will result in a SingleResourceResult with success=false and isDeleted=false
     * @implSpec Reading a deleted resource will result in a SingleResourceResult with both success=true and isDeleted=true
     */
    <T extends Resource> SingleResourceResult<T> read(FHIRPersistenceContext context, Class<T> resourceType, String logicalId)
            throws FHIRPersistenceException;

```
But as you noted, at the moment you can't change the result. Did you consider using the beforeSearch interceptor to inject additional entries to the incoming request bundle? It's not ideal because it means you'll end up evaluating things twice, but it may work as a stop-gap until we are able to implement the return feature discussed above.

**Comment by lmsurpre** [comment]
I updated our sample "TaggingInterceptor" so that it would add tags to all resources being returned from read, vread, history, and search interactions.  Then I issue a request for each of these types and confirmed that the "after" tag appeared the returned resources.
I've opened a pull request at #3858 to deliver my updates to the interceptor in case anyone else would like to play with it.
